package rikka.api.world.biome;

import rikka.api.CatalogType;

public enum BiomeType implements CatalogType {
    BEACH,
    BIRCH_FOREST,
    BIRCH_FOREST_HILLS,
    COLD_BEACH,
    COLD_TAIGA,
    COLD_TAIGA_HILLS,
    DEEP_OCEAN,
    DESERT,
    DESERT_HILLS,
    EXTREME_HILLS,
    EXTREME_HILLS_EDGE,
    EXTREME_HILLS_PLUS,
    FOREST,
    FOREST_HILLS,
    FROZEN_OCEAN,
    FROZEN_RIVER,
    HELL,
    ICE_MOUNTAINS,
    ICE_PLAINS,
    JUNGLE,
    JUNGLE_EDGE,
    JUNGLE_HILLS,
    MEGA_TAIGA,
    MEGA_TAIGA_HILLS,
    MESA,
    MESA_PLATEAU,
    MESA_PLATEAU_FOREST,
    MUSHROOM_ISLAND,
    MUSHROOM_ISLAND_SHORE,
    OCEAN,
    PLAINS,
    RIVER,
    ROOFED_FOREST,
    SAVANNA,
    SAVANNA_PLATEAU,
    SKY,
    STONE_BEACH,
    SWAMPLAND,
    TAIGA,
    TAIGA_HILLS,
    BIRCH_FOREST_HILLS_MOUNTAINS,
    BIRCH_FOREST_MOUNTAINS,
    COLD_TAIGA_MOUNTAINS,
    DESERT_MOUNTAINS,
    EXTREME_HILLS_MOUNTAINS,
    EXTREME_HILLS_PLUS_MOUNTAINS,
    FLOWER_FOREST,
    ICE_PLAINS_SPIKES,
    JUNGLE_EDGE_MOUNTAINS,
    JUNGLE_MOUNTAINS,
    MEGA_SPRUCE_TAIGA,
    MEGA_SPRUCE_TAIGA_HILLS,
    MESA_BRYCE,
    MESA_PLATEAU_FOREST_MOUNTAINS,
    MESA_PLATEAU_MOUNTAINS,
    ROOFED_FOREST_MOUNTAINS,
    SAVANNA_MOUNTAINS,
    SAVANNA_PLATEAU_MOUNTAINS,
    SUNFLOWER_PLAINS,
    SWAMPLAND_MOUNTAINS,
    TAIGA_MOUNTAINS,
    VOID;

    double getTemperature() {
        // TODO
        return 0;
    }

    double getHumidity() {
        // TODO
        return 0;
    }

    public String getId() {
        return null;
    }

    public String getName() {
        return null;
    }
}
